# -*- coding: utf-8 -*-
"""Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GPk25bH32LD-8zp1U0oqTPIuvRfrzcoj
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import MinMaxScaler
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

pd.set_option('display.max_columns', None)

import warnings
warnings.filterwarnings('ignore')

git_url = 'https://raw.githubusercontent.com/shiveshkumar7007/Sales_Forecasting/refs/heads/main/Dataset.csv'
df = pd.read_csv(git_url)

print(df.shape)

print(df.head())

print(df.info())

print(df.describe())

df.columns = (
    df.columns
    .str.lower()
    .str.strip()
    .str.replace(' ', '_')
    .str.replace('(', '')
    .str.replace(')', '')
)

print(df.columns)

print(df.isnull().sum())

print(df.duplicated().sum())

plt.figure(figsize=(10,5))
sns.countplot(data=df, x='category')
plt.title('Category Distribution')
plt.xticks(rotation=45)
plt.show()

plt.figure(figsize=(10,5))
sns.histplot(df['purchase_amount_usd'], bins=30, kde=True)
plt.title('Purchase Amount Distribution')
plt.show()

plt.figure(figsize=(8,5))
sns.boxplot(x=df['review_rating'])
plt.title('Review Rating Distribution')
plt.show()

#FEATURE ENGINEERING
df['discount_flag'] = np.where(df['discount_applied'] == 'Yes', 1, 0)
df['promo_flag'] = np.where(df['promo_code_used'] == 'Yes', 1, 0)
df['subscription_flag'] = np.where(df['subscription_status'] == 'Yes', 1, 0)

print(df.head())

frequency_map = {
    'Weekly': 52,
    'Fortnightly': 26,
    'Monthly': 12,
    'Quarterly': 4,
    'Annually': 1,
    'Bi-Weekly': 26,
    'Every 3 Months': 4
}


df['annual_frequency_score'] = df['frequency_of_purchases'].map(frequency_map)

customer_df = df.groupby('customer_id').agg({
    'age':'first',
    'gender':'first',
    'location':'first',
    'category':lambda x: x.mode()[0],
    'purchase_amount_usd':['sum','mean'],
    'review_rating':'mean',
    'previous_purchases':'mean',
    'annual_frequency_score':'mean',
    'discount_flag':'mean',
    'promo_flag':'mean',
    'subscription_flag':'mean',
    'payment_method':lambda x: x.mode()[0],
    'shipping_type':lambda x: x.mode()[0]
}).reset_index()

customer_df.columns = [
    'customer_id',
    'age',
    'gender',
    'location',
    'favorite_category',
    'total_spend',
    'average_order_value',
    'avg_review_rating',
    'avg_previous_purchases',
    'avg_annual_frequency',
    'discount_dependency_score',
    'promo_dependency_score',
    'subscription_score',
    'preferred_payment_method',
    'preferred_shipping_type'
]

customer_df.head()

conditions = [
    customer_df['avg_review_rating'] >= 4,

    (customer_df['avg_review_rating'] >= 3) &
    (customer_df['avg_review_rating'] < 4),

    customer_df['avg_review_rating'] < 3
]

choices = [
    'High Satisfaction',
    'Neutral',
    'Low Satisfaction'
]

customer_df['satisfaction_flag'] = np.select(
    conditions,
    choices,
    default='Unknown'
)

scaler = MinMaxScaler()

features_to_normalize = [
    'total_spend',
    'average_order_value',
    'avg_previous_purchases',
    'avg_annual_frequency',
    'avg_review_rating',
    'discount_dependency_score',
    'promo_dependency_score',
    'subscription_score'
]

normalized = scaler.fit_transform(customer_df[features_to_normalize])

normalized_df = pd.DataFrame(
    normalized,
    columns=[f'{col}_norm' for col in features_to_normalize]
)

customer_df = pd.concat([customer_df, normalized_df], axis=1)

df.head()

#Loyalty Definition 1 – Revenue Loyalty
#Logic
#Customers are loyal if they:
# 1 spend more
# 2 purchase more frequently
# 3 have more purchase history
customer_df['loyalty_score_1'] = (
    customer_df['total_spend_norm'] * 0.30 +
    customer_df['avg_previous_purchases_norm'] * 0.40 +
    customer_df['avg_annual_frequency_norm'] * 0.30
)

#Loyalty Definition 2 – Quality Loyalty
#Logic
#Customers are loyal if they:
#repeatedly purchase
#are less discount dependent
#subscribe to the brand
#provide strong ratings
customer_df['loyalty_score_2'] = (
    customer_df['avg_previous_purchases_norm'] * 0.30 +
    customer_df['avg_review_rating_norm'] * 0.25 +
    customer_df['subscription_score_norm'] * 0.20 +
    (1 - customer_df['discount_dependency_score_norm']) * 0.25
)

#Compare Loyalty Definitions
corr_1 = customer_df['loyalty_score_1'].corr(customer_df['total_spend'])
corr_2 = customer_df['loyalty_score_2'].corr(customer_df['total_spend'])

print('Correlation of Loyalty Score 1 with Revenue:', corr_1)
print('Correlation of Loyalty Score 2 with Revenue:', corr_2)

#Choose Final Loyalty Score
customer_df['final_loyalty_score'] = (
    customer_df['loyalty_score_1'] * 0.6 +
    customer_df['loyalty_score_2'] * 0.4
)

print(customer_df)

customer_df['value_tier'] = pd.qcut(
    customer_df['total_spend'],
    q=4,
    labels=['Low Value','Medium Value','High Value','Premium Value']
)



conditions = [
    customer_df['discount_dependency_score'] >= 0.75,

    (customer_df['discount_dependency_score'] >= 0.40) &
    (customer_df['discount_dependency_score'] < 0.75),

    customer_df['discount_dependency_score'] < 0.40
]

choices = [
    'Highly Promo Dependent',
    'Moderately Promo Dependent',
    'Low Promo Dependency'
]

customer_df['promo_dependency_segment'] = np.select(
    conditions,
    choices,
    default='Unknown'
)

#customer segmentation
def customer_segment(row):

    if (
        row['final_loyalty_score'] >= 0.70 and
        row['discount_dependency_score'] < 0.40 and
        row['total_spend'] >= customer_df['total_spend'].quantile(0.75)
    ):
        return 'Premium Loyalist'

    elif (
        row['final_loyalty_score'] >= 0.70 and
        row['discount_dependency_score'] >= 0.60
    ):
        return 'Discount Loyalist'

    elif (
        row['final_loyalty_score'] >= 0.50 and
        row['avg_review_rating'] >= 4
    ):
        return 'Potential Loyalist'
    elif (
        row['discount_dependency_score'] >= 0.75 and
        row['total_spend'] < customer_df['total_spend'].median()
    ):
        return 'Bargain Hunter'

    elif (
        row['avg_review_rating'] < 3 and
        row['avg_previous_purchases'] < customer_df['avg_previous_purchases'].median()
    ):
        return 'At Risk'

    else:
        return 'Occasional Customer'


customer_df['customer_segment'] = customer_df.apply(customer_segment, axis=1)

plt.figure(figsize=(12,6))
sns.countplot(data=customer_df, x='customer_segment')
plt.title('Customer Segment Distribution')
plt.xticks(rotation=45)
plt.show()

#revenue by segment
segment_revenue = customer_df.groupby('customer_segment')['total_spend'].sum().sort_values(ascending=False)

plt.figure(figsize=(12,6))
segment_revenue.plot(kind='bar')
plt.title('Revenue Contribution by Segment')
plt.ylabel('Revenue')
plt.show()

#Promo Dependency vs Loyalty
plt.figure(figsize=(10,6))

sns.scatterplot(
    data=customer_df,
    x='discount_dependency_score',
    y='final_loyalty_score',
    hue='customer_segment',
    size='total_spend'
)

plt.title('Promo Dependency vs Loyalty')
plt.show()

#Geographic Opportunity Analysis
geo_analysis = customer_df.groupby('location').agg({
    'customer_id':'count',
    'total_spend':'mean',
    'discount_dependency_score':'mean',
    'final_loyalty_score':'mean'
}).reset_index()

geo_analysis.columns = [
    'location',
    'customers',
    'avg_spend',
    'avg_discount_dependency',
    'avg_loyalty'
]

geo_analysis.sort_values('avg_spend', ascending=False).head(10)

#Top Organic Demand Regions
#Organic demand regions =
#High spend
#Low promo dependency
organic_regions = geo_analysis[
    (geo_analysis['avg_spend'] > geo_analysis['avg_spend'].median()) &
    (geo_analysis['avg_discount_dependency'] < geo_analysis['avg_discount_dependency'].median())
]

organic_regions.sort_values('avg_spend', ascending=False)

#Category Loyalty Analysis
category_analysis = df.groupby('category').agg({
    'purchase_amount_usd':'mean',
    'previous_purchases':'mean',
    'review_rating':'mean'
}).reset_index()

category_analysis.columns = [
    'category',
    'avg_spend',
    'avg_previous_purchases',
    'avg_rating'
]

category_analysis

#Category Funnel Visualization
plt.figure(figsize=(10,6))

sns.scatterplot(
    data=category_analysis,
    x='avg_previous_purchases',
    y='avg_spend',
    size='avg_rating',
    hue='category'
)

plt.title('Category Funnel Analysis')
plt.show()

#Payment Preference Analysis
payment_analysis = customer_df.groupby('preferred_payment_method').agg({
    'total_spend':'mean',
    'final_loyalty_score':'mean'
}).sort_values('total_spend', ascending=False)

payment_analysis

#Subscription Impact Analysis
subscription_analysis = customer_df.groupby('subscription_score').agg({
    'total_spend':'mean',
    'final_loyalty_score':'mean',
    'discount_dependency_score':'mean'
})

subscription_analysis

#Pareto Analysis (80/20 Rule)
pareto_df = customer_df.sort_values('total_spend', ascending=False)

pareto_df['cum_revenue'] = pareto_df['total_spend'].cumsum()
pareto_df['cum_revenue_pct'] = (
    pareto_df['cum_revenue'] /
    pareto_df['total_spend'].sum()
)

pareto_df['customer_pct'] = np.arange(1, len(pareto_df)+1) / len(pareto_df)

print(pareto_df)

plt.figure(figsize=(10,6))

plt.plot(
    pareto_df['customer_pct'],
    pareto_df['cum_revenue_pct']
)

plt.axhline(0.80, linestyle='--')
plt.axvline(0.20, linestyle='--')

plt.title('Pareto Analysis')
plt.xlabel('Customer Percentage')
plt.ylabel('Cumulative Revenue Percentage')

plt.show()

cluster_features = customer_df[[
    'total_spend_norm',
    'avg_previous_purchases_norm',
    'discount_dependency_score_norm',
    'avg_review_rating_norm',
    'subscription_score_norm'
]]

cluster_features.isnull().sum()

cluster_features.isnull().sum().sum()

cluster_features = cluster_features.fillna(
    cluster_features.median()
)



inertia = []

for k in range(2, 10):
    kmeans = KMeans(n_clusters=k, random_state=42)
    kmeans.fit(cluster_features)
    inertia.append(kmeans.inertia_)

plt.figure(figsize=(8,5))
plt.plot(range(2,10), inertia, marker='o')
plt.title('Elbow Method')
plt.xlabel('K')
plt.ylabel('Inertia')
plt.show()

kmeans = KMeans(n_clusters=4, random_state=42)

customer_df['cluster'] = kmeans.fit_predict(cluster_features)

cluster_profile = customer_df.groupby('cluster').agg({
    'total_spend':'mean',
    'avg_previous_purchases':'mean',
    'discount_dependency_score':'mean',
    'avg_review_rating':'mean',
    'final_loyalty_score':'mean'
})

cluster_profile

#High-Value Customers
high_value = customer_df[
    customer_df['value_tier'] == 'Premium Value'
]

high_value.describe()

#Discount-Dependent Customers
discount_customers = customer_df[
    customer_df['discount_dependency_score'] >= 0.75
]

print(discount_customers.shape)

#Revenue Share from Promo-Dependent Users
promo_revenue_share = (
    discount_customers['total_spend'].sum() /
    customer_df['total_spend'].sum()
)

print('Revenue share from highly promo-dependent customers:', promo_revenue_share)

#Strategic Recommendation Variables
#Identify Customers Suitable for Promo Sunset
promo_sunset_candidates = customer_df[
    (customer_df['customer_segment'] == 'Premium Loyalist') &
    (customer_df['discount_dependency_score'] < 0.30)
]

promo_sunset_candidates.head()

#Ideal Customer Profile Extraction
ideal_customers = customer_df[
    (customer_df['final_loyalty_score'] >= 0.75) &
    (customer_df['discount_dependency_score'] < 0.40)
]

ideal_customers.groupby([
    'gender',
    'favorite_category',
    'preferred_payment_method'
]).agg({
    'age':'mean',
    'total_spend':'mean'
}).sort_values('total_spend', ascending=False)

customer_df.to_csv('customer_features.csv', index=False)

geo_analysis.to_csv('geography_analysis.csv', index=False)

category_analysis.to_csv('category_analysis.csv', index=False)

segment_analysis = (
    customer_df
    .groupby('customer_segment')
    .agg({
        'customer_id':'count',
        'total_spend':'mean',
        'final_loyalty_score':'mean',
        'discount_dependency_score':'mean',
        'avg_review_rating':'mean'
    })
    .reset_index()
)

segment_analysis.columns = [
    'customer_segment',
    'customers',
    'avg_spend',
    'avg_loyalty',
    'avg_discount_dependency',
    'avg_rating'
]

segment_analysis

segment_analysis.to_csv(
    'segment_analysis.csv',
    index=False
)